"""
tools/report_generator.py — Multi-format report exporter (MD / PDF / DOCX).
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict, List

from loguru import logger


# ── Data helpers ───────────────────────────────────────────────────────────────

def _safe(text: Any, default: str = "") -> str:
    return str(text).strip() if text else default


def build_markdown(report_data: Dict) -> str:
    """Render report_data dict into a Markdown string."""
    topic = _safe(report_data.get("topic"), "Research Report")
    ts = report_data.get("generated_at", time.strftime("%Y-%m-%d %H:%M"))
    sections = report_data.get("sections", {})
    papers = report_data.get("papers", [])
    citations = report_data.get("citations", [])

    lines: List[str] = [
        f"# {topic}",
        f"> *Generated by ResearchPilot-AI on {ts}*",
        "",
    ]

    section_order = [
        ("introduction", "1. Introduction"),
        ("related_work", "2. Related Work"),
        ("method_comparison", "3. Methodology Comparison"),
        ("key_findings", "4. Key Findings"),
        ("challenges", "5. Challenges & Limitations"),
        ("future_work", "6. Future Work"),
    ]

    for key, heading in section_order:
        content = _safe(sections.get(key))
        if content:
            lines += [f"## {heading}", "", content, ""]

    # Papers table
    if papers:
        lines += ["## Analyzed Papers", ""]
        lines += ["| # | Title | Authors | Published |",
                  "|---|-------|---------|-----------|"]
        for i, p in enumerate(papers, 1):
            title = _safe(p.get("title", ""))[:60]
            authors = ", ".join(p.get("authors", [])[:2])
            if len(p.get("authors", [])) > 2:
                authors += " et al."
            pub = _safe(p.get("published"))
            lines.append(f"| {i} | {title} | {authors} | {pub} |")
        lines.append("")

    # References
    if citations:
        lines += ["## References", ""]
        for c in citations:
            lines.append(f"- {_safe(c)}")
        lines.append("")

    return "\n".join(lines)


def export_markdown(report_data: Dict, output_path: Path) -> Path:
    """Write report as Markdown file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    md = build_markdown(report_data)
    output_path.write_text(md, encoding="utf-8")
    logger.info(f"Markdown report saved: {output_path}")
    return output_path


def export_pdf(report_data: Dict, output_path: Path) -> Path:
    """Write report as PDF using ReportLab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, HRFlowable,
            Table, TableStyle, PageBreak,
        )
    except ImportError:
        logger.error("reportlab not installed. Falling back to Markdown.")
        return export_markdown(report_data, output_path.with_suffix(".md"))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(output_path), pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
    )
    h1_style = ParagraphStyle(
        "H1", parent=styles["Heading1"],
        fontSize=14, textColor=colors.HexColor("#16213e"),
        spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["BodyText"],
        fontSize=10, leading=15, spaceAfter=8,
    )
    caption_style = ParagraphStyle(
        "Caption", parent=styles["Italic"],
        fontSize=9, textColor=colors.grey, spaceAfter=16,
    )

    topic = _safe(report_data.get("topic"), "Research Report")
    ts = report_data.get("generated_at", time.strftime("%Y-%m-%d %H:%M"))
    sections = report_data.get("sections", {})
    papers = report_data.get("papers", [])
    citations = report_data.get("citations", [])

    story = [
        Paragraph(topic, title_style),
        Paragraph(f"Generated by ResearchPilot-AI · {ts}", caption_style),
        HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#6c63ff")),
        Spacer(1, 0.4*cm),
    ]

    section_order = [
        ("introduction", "1. Introduction"),
        ("related_work", "2. Related Work"),
        ("method_comparison", "3. Methodology Comparison"),
        ("key_findings", "4. Key Findings"),
        ("challenges", "5. Challenges & Limitations"),
        ("future_work", "6. Future Work"),
    ]
    for key, heading in section_order:
        content = _safe(sections.get(key))
        if content:
            story.append(Paragraph(heading, h1_style))
            for para in content.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), body_style))
            story.append(Spacer(1, 0.3*cm))

    # Papers table
    if papers:
        story.append(Paragraph("Analyzed Papers", h1_style))
        table_data = [["#", "Title", "Authors", "Published"]]
        for i, p in enumerate(papers, 1):
            title = _safe(p.get("title", ""))[:50]
            authors = ", ".join(p.get("authors", [])[:2])
            if len(p.get("authors", [])) > 2:
                authors += " et al."
            table_data.append([str(i), title, authors, _safe(p.get("published"))])
        t = Table(table_data, colWidths=[1*cm, 8*cm, 5*cm, 3*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6c63ff")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.HexColor("#f0f0ff"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.4*cm))

    # References
    if citations:
        story.append(Paragraph("References", h1_style))
        for c in citations:
            story.append(Paragraph(f"• {_safe(c)}", body_style))

    doc.build(story)
    logger.info(f"PDF report saved: {output_path}")
    return output_path


def export_docx(report_data: Dict, output_path: Path) -> Path:
    """Write report as DOCX using python-docx."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        logger.error("python-docx not installed. Falling back to Markdown.")
        return export_markdown(report_data, output_path.with_suffix(".md"))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = Document()

    # Styles
    topic = _safe(report_data.get("topic"), "Research Report")
    ts = report_data.get("generated_at", time.strftime("%Y-%m-%d %H:%M"))
    sections = report_data.get("sections", {})
    papers = report_data.get("papers", [])
    citations = report_data.get("citations", [])

    t = doc.add_heading(topic, level=0)
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph(f"Generated by ResearchPilot-AI · {ts}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x99)
    sub.runs[0].font.size = Pt(10)

    doc.add_paragraph()

    section_order = [
        ("introduction", "1. Introduction"),
        ("related_work", "2. Related Work"),
        ("method_comparison", "3. Methodology Comparison"),
        ("key_findings", "4. Key Findings"),
        ("challenges", "5. Challenges & Limitations"),
        ("future_work", "6. Future Work"),
    ]
    for key, heading in section_order:
        content = _safe(sections.get(key))
        if content:
            doc.add_heading(heading, level=1)
            for para in content.split("\n\n"):
                if para.strip():
                    doc.add_paragraph(para.strip())

    if papers:
        doc.add_heading("Analyzed Papers", level=1)
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        for i, h in enumerate(["#", "Title", "Authors", "Published"]):
            hdr[i].text = h
        for i, p in enumerate(papers, 1):
            row = table.add_row().cells
            row[0].text = str(i)
            row[1].text = _safe(p.get("title", ""))[:60]
            authors = ", ".join(p.get("authors", [])[:2])
            if len(p.get("authors", [])) > 2:
                authors += " et al."
            row[2].text = authors
            row[3].text = _safe(p.get("published"))
        doc.add_paragraph()

    if citations:
        doc.add_heading("References", level=1)
        for c in citations:
            doc.add_paragraph(_safe(c), style="List Bullet")

    doc.save(str(output_path))
    logger.info(f"DOCX report saved: {output_path}")
    return output_path


def export_report(report_data: Dict, output_dir: Path,
                  session_id: str, fmt: str = "pdf") -> Path:
    """
    Master export function. fmt in {'pdf', 'md', 'docx'}.
    Returns path to generated file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"report_{session_id}"
    fmt = fmt.lower().strip(".")

    if fmt == "pdf":
        return export_pdf(report_data, output_dir / f"{stem}.pdf")
    elif fmt == "docx":
        return export_docx(report_data, output_dir / f"{stem}.docx")
    else:
        return export_markdown(report_data, output_dir / f"{stem}.md")
